name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Update to the latest version
    - name: Set up Python
      uses: actions/setup-python@v4  # Update to the latest version
      with:
        python-version: '3.x'  # Specify the version of Python to use
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
