name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # This is still the correct version; it will use Node 20
    - name: Set up Python
      uses: actions/setup-python@v4  # This is still the correct version; it will use Node 20
      with:
        python-version: '3.x'  # Specify the version of Python to use
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
